### ISSUE TITLE
Hubo un Error al poner Mercado Pago

### ISSUE THREAD

**Issue by matiasanu** [garymartin87/videocallshop-api#41]
Hola Maurito como andas? Al poner Mercado Pago me pone Hubo un error. Hice una llamada a la tienda de La Elena. Deje la orden de compra igual y en vez de poner Mercado Pago puse Pago en domicilio y me la guardo bien.

**Comment by garymartin87** [comment]
Esto puede ser backend, @maurocg89 si podes reproducirlo y es de api mandame la respuesta del metodo y lo miro.

**Comment by matiasanu** [comment]
Hoy lo volvi a probar en stage Gary y sigue sin funcionar cualquier combinacion con mercado pago el resto anda bien

**Comment by matiasanu** [comment]
Hubo 1 orden de compra que si me tomo pero despues me empezo a tirar error igual que la otra vez
![Screenshot_20200429-205042_Gmail](https://user-images.githubusercontent.com/50674449/80657956-4c996600-8a5b-11ea-99f1-77ab8dcecd29.jpg)
![Screenshot_20200429-205307_Email](https://user-images.githubusercontent.com/50674449/80658144-b31e8400-8a5b-11ea-9482-2389cefce871.jpg)
En este lector de mail no me salio en azul el link como si me salio en el 1ero. Eso no se como se podra solucionar, quizas tambien seria conveniente sacar el punto del final porque si alguien copia el link completo y agrega el punto le va a tirar error, se tiene que dar cuenta de copiarlo sin el punto.
![Screenshot_20200429-205801_Chrome](https://user-images.githubusercontent.com/50674449/80658302-2cb67200-8a5c-11ea-9112-3bf4d54751e1.jpg)

Me entro bien en este caso que me dejo cerrar la orden de compra, luego empezo a tirar "Hubo un error"

**Comment by matiasanu** [comment]
en dev anda bien el mercado pago

**Comment by garymartin87** [comment]
```
Generating MERCADOPAGO PRODUCTIVE link { client_id: '8649637676151674',

2020-04-30T19:20:22.747334+00:00 app[web.1]:   client_secret: '9DPHVhnBv2It5qZYBqiQtigtrHJPiCoT' }

2020-04-30T19:20:22.748054+00:00 app[web.1]: { Error: Cant change client_id or client_secret because is already set

2020-04-30T19:20:22.748055+00:00 app[web.1]:     at Object.configurationsModule.configure (/app/node_modules/mercadopago/lib/configurations.js:40:11)

2020-04-30T19:20:22.748056+00:00 app[web.1]:     at Function.configure (/app/node_modules/mercadopago/lib/mercadopago.js:20:18)

2020-04-30T19:20:22.748057+00:00 app[web.1]:     at Object.createPreference (/app/helpers/mercadopago.js:23:8)

2020-04-30T19:20:22.748057+00:00 app[web.1]:     at createPurchaseOrder (/app/controllers/purchaseOrder.js:87:61)

2020-04-30T19:20:22.748057+00:00 app[web.1]:     at processTicksAndRejections (internal/process/next_tick.js:81:5) status: 500 }

2020-04-30T19:20:22.752659+00:00 app[web.1]: [0mPOST /stores/3/call-requests/350/purchase-orders/ [31m500 [0m14.879 ms - 55[0m
```

**Comment by matiasanu** [comment]
![Error Mercado pado](https://user-images.githubusercontent.com/50674449/80843959-eb4cd080-8bdb-11ea-9195-5fe65f7c9c19.png)
Hoy probe con la nueva tienda en Sport 78 en Stage (que le cargue mi mercado pago personal de matiasanu@gmail.com)

La primerta orden de compra me la tomo bien
Ya la 2da orden de compra me tira error y no me la deja Guardar.
